apiVersion: v1
kind: Service
metadata:
  name: datanexus-backend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: datanexus-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
